name: Printer Lab

on:
  workflow_dispatch:
    inputs:
      printerName:
        description: Printer folder name
        required: true
        default: HP-LJPro-M401

jobs:
  build-printer:

    runs-on: [self-hosted, windows, intune-test]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Printer Structure
        shell: pwsh
        run: |
          Get-ChildItem .\apps\printers -Recurse

      - name: Show Selected Printer
        shell: pwsh
        run: |
          Write-Host "Printer:"
          Write-Host "${{ github.event.inputs.printerName }}"

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: printer-lab-output
          path: apps/printers