name: Winget Update Check

on:
  workflow_dispatch:

  schedule:
    - cron: '0 2 * * 0'

permissions:
  contents: write
  pull-requests: write

jobs:

  winget-update-check:
    if: github.actor != 'github-actions[bot]'
    
    runs-on: [self-hosted, windows, intune-test]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_BOT_TOKEN }}

      - name: Verify Git
        shell: pwsh
        run: |
            git --version

      - name: Run Winget Update Check
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_BOT_TOKEN }}
        run: |
          ./scripts/Update-WingetApps.ps1

      - name: Create Pull Request
        if: env.BRANCH_NAME != ''
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_BOT_TOKEN }}
        run: |
          $appTags = $env:UPDATED_APPS -replace ',', '] [app:'
          $title = "Automated WinGet Updates [app:$appTags]"
          $body = @"
          The following applications were updated automatically:
          
          $env:UPDATED_APPS

          Genereated by Intune App Factory WinGet Update Check.
          "@
          
          gh pr create --base main --head $env:BRANCH_NAME --title "$title" --body "$body"